### ISSUE TITLE
crashes on an attempt to restart a worker

### ISSUE THREAD

**Issue by ravendyg** [ravendyg/tor-proxy#10]
/usr/src/app/lib/clustering/master.js:56
        workers[restarting].send({action: 'close', id: restarting});
                           ^

TypeError: Cannot read property 'send' of undefined
    at Timeout.restart [as _onTimeout] (/usr/src/app/lib/clustering/master.js:56:28)
    at ontimeout (timers.js:380:14)
    at tryOnTimeout (timers.js:244:5)
    at Timer.listOnTimeout (timers.js:214:5)

npm info lifecycle tor-proxy@0.0.1~start: Failed to exec start script

**Comment by ravendyg** [comment]
fixed
